# Generated by Django 2.0.5 on 2018-11-12 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_Title', models.CharField(max_length=200)),
                ('campaign_Tagline', models.CharField(max_length=200)),
                ('campaign_Card_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('campaign_Category', models.CharField(choices=[('creative', (('comics', 'comics'), ('art', 'art'))), ('tech', (('education', 'education'), ('phones', 'phones'))), ('community', (('environment', 'environment'), ('culture', 'culture')))], max_length=20)),
                ('country', models.CharField(default='India', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', models.TextField(max_length=500)),
                ('story', models.TextField(blank=True, max_length=500, null=True)),
                ('goal', models.FloatField()),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('pledged', models.FloatField(default=0.0)),
                ('people_pledged', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=100)),
                ('answer', models.TextField(blank=True, max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
