# Generated by Django 2.0.5 on 2018-11-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_Title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('campaign_Title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funds.Campaign')),
            ],
        ),
    ]
